src/main/java/sv/edu/uesocc/ingenieria/prn335_2017/web/controladores/GenericManagedBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sv.edu.uesocc.ingenieria.prn335_2017.web.controladores;

import java.io.Serializable;
import java.util.Collections;
import java.util.List;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import sv.edu.uesocc.ingenieria.prn335_2017.datos.acceso.GenericFacadeLocal;

/**
 *
 * @author carlos
 */
public abstract class GenericManagedBean<T> implements Serializable {

    List<T> listaDatos;

    /**
     * Este metodo sirve para crear un nuevo un registro
     */
    public void crear() {
        if (getFacadeLocal() != null) {
            try {
                System.out.println("Llego aqui");
                getFacadeLocal().create(getEntity());
                llenarLista();
                reset();
                enviarMensaje(false,"Registro creado correctamente.");
            } catch (Exception ex) {
                System.out.println("Error: " + ex);
                enviarMensaje(true,"Error al crear registro creado correctamente.");
            }
        }
    }

    /**
     * Este metodo sirve para editar un registro
     */
    public void editar() {
        if (getFacadeLocal() != null) {
            try {
                System.out.println("Llego aqui");
                getFacadeLocal().edit(getEntity());
                llenarLista();
                reset();
                enviarMensaje(false,"Edicion realizada correctamente.");
            } catch (Exception ex) {
                System.out.println("Error: " + ex);
                enviarMensaje(true,"Error al editar registro.");
            }
        }
    }

    /**
     * Este metodo sirve para eliminar un registro
     */
    public void eliminar() {
        if (getFacadeLocal() != null) {
            try {
                System.out.println("Llego aqui");
                getFacadeLocal().remove(getEntity());
                llenarLista();
                reset();
                enviarMensaje(false,"Registro eliminado correctamente");
            } catch (Exception ex) {
                System.out.println("Error: " + ex);
                enviarMensaje(true,"Error al eliminar registro");
            }
        }
    }

    /**
     * Este metodo sirve para llenar una lista de datos obtenidos de la base de
     * datos
     */
    public void llenarLista() {
        if (getFacadeLocal().findAll() != null) {
            this.listaDatos = getFacadeLocal().findAll();
        } else {
            this.listaDatos = Collections.EMPTY_LIST;
        }
    }

    /**
     * Este metodo sirve para mostrar un mensaje en el JSF
     *
     * @param error espera un true o false para mostrar un mensaje de error o
     * confirmacion respectivaente
     * @param mensaje espera el mensaje a mostrar
     */
    public void enviarMensaje(boolean error, String mensaje) {
        if (error=false) {
            FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_INFO, "Info", mensaje));
        } else {
            FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_ERROR, "Info", mensaje));
        }
    }

    /**
     * 
     * @return se espera que retorne el una interfaz de algun tipo para trabajar con ell
     */
    protected abstract GenericFacadeLocal<T> getFacadeLocal();

    /**
     *
     * @return se espera que retorne una entitdad para trabajar con ella
     */
    public abstract T getEntity();
    
    public abstract void nuevo();
    
    public abstract void cancelar();
    
    public abstract void reset();

}

src/main/java/sv/edu/uesocc/ingenieria/prn335_2017/web/controladores/TipoPostBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sv.edu.uesocc.ingenieria.prn335_2017.web.controladores;

import java.io.Serializable;
import java.util.List;
import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.inject.Named;
import javax.faces.view.ViewScoped;
import org.primefaces.event.SelectEvent;
import sv.edu.uesocc.ingenieria.prn335_2017.datos.acceso.GenericFacadeLocal;
import sv.edu.uesocc.ingenieria.prn335_2017.datos.acceso.TipoPostFacadeLocal;
import sv.edu.uesocc.ingenieria.prn335_2017.datos.definiciones.TipoPost;
/**
 *
 * @author carlos
 */
@Named(value = "tipoPostBean")
@ViewScoped
public class TipoPostBean extends GenericManagedBean<TipoPost> implements Serializable{

    /**
     * Creates a new instance of TipoPostBean
     */
    public TipoPostBean() {
    }
    @EJB
    TipoPostFacadeLocal facade;
    TipoPost tipoEntity;
    boolean mostrar = false, crudBtns=true;  
    
    
    // <editor-fold defaultstate="collapsed" desc="Getters y Setters">
    public TipoPostFacadeLocal getFacade() {
        return facade;
    }

    public boolean isMostrar() {
        return mostrar;
    }

    public boolean isCrudBtns() {
        return crudBtns;
    }

    public void setCrudBtns(boolean crudBtns) {
        this.crudBtns = crudBtns;
    }

    public void setMostrar(boolean mostrar) {
        this.mostrar = mostrar;
    }

    public void setFacade(TipoPostFacadeLocal facade) {
        this.facade = facade;
    }

    public TipoPost getTipoPostEntity() {
        return tipoEntity;
    }

    public void setTipoPostEntity(TipoPost tipoEntity) {
        this.tipoEntity = tipoEntity;
    }

    public List<TipoPost> getListaDatos() {
        return listaDatos;
    }

    public void setListaDatos(List<TipoPost> listaDatos) {
        this.listaDatos = listaDatos;
    }
    // </editor-fold>

    // <editor-fold defaultstate="collapsed" desc="Overrrides">
    @Override
    public TipoPost getEntity() {
        return tipoEntity;
    }

    @Override
    protected GenericFacadeLocal<TipoPost> getFacadeLocal() {
        return facade;
    }

   @Override
    public void reset() {
        tipoEntity.setActivo(false);
        tipoEntity.setNombre(null);
        tipoEntity.setDescripcion(null);
        
    }

    @Override
    public void nuevo() {
        tipoEntity = new TipoPost();
        setMostrar(true);
        setCrudBtns(true);
    }
    
    @Override
    public void cancelar(){
        tipoEntity = new TipoPost();
        setMostrar(false);
        setCrudBtns(true);
    }
    
    // </editor-fold>

    @PostConstruct
    public void init() {
        llenarLista();
    }
    
    /**
     * Este metodo sirve para mostrar el la fila seleccionada en un formulario para ser editado o eliminado
     * @param event 
     */
    public void onRowSelect(SelectEvent event) {
        setCrudBtns(false);
        setMostrar(true);
    }
    
    
}

src/main/webapp/WEB-INF/pages/tipopost/Formulario.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:p="http://primefaces.org/ui"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns:ez="http://xmlns.jcp.org/jsf/composite/ezcomp">

    <h:form id="formulario" >
        <p:panel id="manejoDatos" rendered="#{tipoPostBean.mostrar}">
            <div align="center">
                <p:messages id="messages" showDetail="true" autoUpdate="true" closable="true" />
            </div>
            <p:panelGrid columns="2">
                <p:outputLabel value="#{componente['prop.name']}: " for="nombre" />
                <p:inputText id="nombre" value="#{tipoPostBean.tipoPostEntity.nombre}" title="Nombre" required="true" requiredMessage="#{componente['error.guardar']}"/>
                <p:outputLabel value="#{componente['prop.active']}:" for="activo" />
                <p:selectBooleanCheckbox id="activo" value="#{tipoPostBean.tipoPostEntity.activo}" />
                <p:outputLabel value="#{componente['prop.descripcion']}:" for="descripcion" />
                <p:inputText id="descripcion" value="#{tipoPostBean.tipoPostEntity.descripcion}" title="Descripcion" required="true" requiredMessage="#{componente['error.descripcion']}"/>
                </p:panelGrid>
            <div>
                <ez:BotonCRUD listener="#{tipoPostBean}" renderBtns="#{tipoPostBean.crudBtns}" updates="@form :tabla" />
            </div>
        </p:panel>
    </h:form>

</ui:composition>

src/main/webapp/WEB-INF/pages/tipopost/Tabla.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:p="http://primefaces.org/ui"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns:ez="http://xmlns.jcp.org/jsf/composite/ezcomp">
    
    <h:form id="tabla">
        <h1 align="center"><h:outputText value="#{componente['user.title']}"/></h1>
        <p:dataTable id="tabla"
                     value="#{tipoPostBean.listaDatos}"
                     lazy="false"
                     rowKey="#{item.idTipoPost}"
                     var="item"
                     paginator="true"
                     rows="6"
                     rowsPerPageTemplate="5,10,15,20,25"
                     selectionMode="single"
                     selection="#{tipoPostBean.tipoPostEntity}">

            <p:ajax event="rowSelect" listener="#{tipoPostBean.onRowSelect}" update=":formulario"/>

            <p:column sortBy="#{item.idTipoPost}" >
                <f:facet name="header">
                    <h:outputText value="#{componente['prop.id']}"/>
                </f:facet>
                <h:outputText value="#{item.idTipoPost}"/>
            </p:column>

            <p:column sortBy="#{item.nombre}" >
                <f:facet name="header">
                    <h:outputText value="#{componente['prop.name']}"/>
                </f:facet>
                <h:outputText value="#{item.nombre}"/>
            </p:column>

            <p:column>
                <f:facet name="header">
                    <h:outputText value="#{componente['prop.active']}"/>
                </f:facet>
                <h:outputText value="#{item.activo}"/>
            </p:column>
            <p:column sortBy="#{item.descripcion}" >
                <f:facet name="header">
                    <h:outputText value="#{componente['prop.descripcion']}"/>
                </f:facet>
                <h:outputText value="#{item.descripcion}"/>
            </p:column>

        </p:dataTable>
        <ez:BotonMotrarOcultar listener="#{tipoPostBean}" updates="@form :formulario" />
    </h:form>

</ui:composition>

src/main/webapp/WEB-INF/plantilla/plantilla.xhtml
<?xml version='1.0' encoding='UTF-8' ?> 
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <h:head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <title>#{componente['user.title']}</title>
    </h:head>

    <h:body>
        <p:layout fullPage="true">
            <p:layoutUnit position="north" size="7%" style="border: none">
                <ui:insert name="header">
                    <h:form>
                        <p:outputLabel for="idiomas" value="#{componente['page.languajes']}  "/>
                        <h:selectOneListbox id="idiomas" size="1" value="#{managedLanguajes.idioma}" 
                                         valueChangeListener="#{managedLanguajes.cambioDeIdioma}"
                                         onchange="submit()">
                            <f:selectItems value="#{managedLanguajes.paises}"/>
                        </h:selectOneListbox>
                    </h:form>                
                </ui:insert>
            </p:layoutUnit>

            <p:layoutUnit position="center" style="border: none">
                <ui:insert name="body"/>
            </p:layoutUnit>

            <p:layoutUnit position="south" size="7%" style="border: none">
                <ui:insert name="footer">
                    #{componente['page.copy']}
                </ui:insert>
            </p:layoutUnit>
        </p:layout>

    </h:body>

</html>

src/main/webapp/index.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    
     <h:head>
         <title>#{componente['user.title']}</title>
    </h:head>
    <h:body>
        <ui:composition template="WEB-INF/plantilla/plantilla.xhtml">
            <ui:define name="body">

                <f:view>
                    <ui:include src="WEB-INF/pages/tipopost/Tabla.xhtml" />
                    <ui:include src="WEB-INF/pages/tipopost/Formulario.xhtml" />
                </f:view>
            </ui:define>
        </ui:composition>
    </h:body>
</html>

src/main/webapp/resources/ezcomp/BotonCRUD.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:cc="http://xmlns.jcp.org/jsf/composite"
      xmlns:p="http://primefaces.org/ui">

    <!-- INTERFACE -->
    <cc:interface>
        <cc:attribute name="listener" required="true" type="sv.edu.uesocc.ingenieria.prn335_2017.web.controladores.GenericManagedBean"/>
        <cc:attribute name="updates" required="true" type="java.lang.String" />
        <cc:attribute name="renderBtns" required="true" type="java.lang.Boolean"/>
        <cc:attribute name="entidad" rendered="false" type="java.lang.String" default="" />
         
    </cc:interface>

    <!-- IMPLEMENTATION -->
    <cc:implementation>
        <p:commandButton value="#{componente['crud.new']} #{cc.attrs.entidad}" actionListener="#{cc.attrs.listener.crear()}" update="#{cc.attrs.updates}" rendered="#{cc.attrs.renderBtns}" />
        <p:commandButton value="#{componente['crud.edit']}  #{cc.attrs.entidad}" actionListener="#{cc.attrs.listener.editar()}" update="#{cc.attrs.updates}" rendered="#{!cc.attrs.renderBtns}" />
        <p:commandButton value="#{componente['crud.delete']}  #{cc.attrs.entidad}" actionListener="#{cc.attrs.listener.eliminar()}" update="#{cc.attrs.updates}" rendered="#{!cc.attrs.renderBtns}" />
    </cc:implementation>
</html>

src/main/webapp/resources/ezcomp/BotonMotrarOcultar.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:cc="http://xmlns.jcp.org/jsf/composite"
      xmlns:p="http://primefaces.org/ui">

    <!-- INTERFACE -->
    <cc:interface>
        <cc:attribute name="listener" required="true" type="sv.edu.uesocc.ingenieria.prn335_2017.web.controladores.GenericManagedBean"/>
        <cc:attribute name="updates" required="true" type="java.lang.String" />
        <cc:attribute name="entidad" required="false" type="java.lang.String" default="" />
</cc:interface>

    <!-- IMPLEMENTATION -->
    <cc:implementation>
        <p:commandButton value="#{componente['crud.new']} #{cc.attrs.entidad}" actionListener="#{cc.attrs.listener.nuevo()}" update="#{cc.attrs.updates}"/>
        <p:commandButton value="#{componente['crud.cancel']} #{cc.attrs.entidad}" actionListener="#{cc.attrs.listener.cancelar()}" update="#{cc.attrs.updates}"/>
    </cc:implementation>
</html>

src/main/webapp/welcomePrimefaces.xhtml
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui">

    <f:view contentType="text/html">
        <h:head>
            <f:facet name="first">
                <meta content='text/html; charset=UTF-8' http-equiv="Content-Type"/>
                <title>PrimeFaces</title>
            </f:facet>
        </h:head>

        <h:body>

            <p:layout fullPage="true">

                <p:layoutUnit position="north" size="100" resizable="true" closable="true" collapsible="true">
                    Header
                </p:layoutUnit>

                <p:layoutUnit position="south" size="100" closable="true" collapsible="true">
                    Footer
                </p:layoutUnit>

                <p:layoutUnit position="west" size="175" header="Left" collapsible="true">
                    <p:menu>
                        <p:submenu label="Resources">
                            <p:menuitem value="Demo" url="http://www.primefaces.org/showcase-labs/ui/home.jsf" />
                            <p:menuitem value="Documentation" url="http://www.primefaces.org/documentation.html" />
                            <p:menuitem value="Forum" url="http://forum.primefaces.org/" />
                            <p:menuitem value="Themes" url="http://www.primefaces.org/themes.html" />

                        </p:submenu>

                    </p:menu>
                </p:layoutUnit>

                <p:layoutUnit position="center">
                    Welcome to PrimeFaces
                </p:layoutUnit>

            </p:layout>

        </h:body>

    </f:view>
</html>